import '../../styles/globals.scss'
import { Inter } from 'next/font/google'
import SideNavBar from '@/components/SideBar/SideNavBar';
// import Sidebar from '@/components/Sidebar';
import Header from '@/components/SideBar/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <main style={{background: 'rgb(209, 213, 219)', minHeight: '100vh'}}>
      <Header/>
      </main> */}
      {/* <Sidebar /> */}
      <SideNavBar/>
      <div style={{marginLeft: "72px"}}>{children}</div>
      </body>
    </html>
  )
}
